
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DATABASES:user?createDatabaseIfNotExist=true}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    open-in-view: true

server:
  port: ${SERVER_PORT:8000}



security:
  access_token:
    secret_key: 4125442A472D4B6150645367566B59703373357638792F423F4528482B4D6251
    live: 1000000
  refresh_token:
    secret_key: 432A462D4A614E645267556B586E3272357538782F413F4428472B4B62506553
    live: 100000

# CONSTANTS
constants:
  token-prefix: "Bearer "
  refresh-token-api: "/auth/token/refresh"
  header-string: "Authorization"
